# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <DevHistory>
email: midia.matheus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Todo mundo tem histórias pra contar, principalmente os desenvolvedores! 
  Então, se você é um desenvolvedor(iniciante ou expert), conte-nos sua história! Hahaha
baseurl: "/devhistory" # the subpath of your site, e.g. /blog
url: "http://www.pineb.com.br/devhistory" # the base hostname & protocol for your site
twitter_username: devhernandes
github_username:  devhernandes

# Build settings
markdown: kramdown
permalink: /:title/